var N = null;var sourcesIndex = {};
sourcesIndex["jamsocket"] = {"name":"","files":["jamsocket.rs"]};
sourcesIndex["jamsocket_api"] = {"name":"","files":["lib.rs"]};
sourcesIndex["jamsocket_cli"] = {"name":"","dirs":[{"name":"commands","files":["deploy.rs","dev.rs","login.rs","mod.rs","register.rs","serve.rs"]}],"files":["cli_opts.rs","config.rs","lib.rs"]};
sourcesIndex["jamsocket_server"] = {"name":"","files":["client_socket_connection.rs","connection_info.rs","lib.rs","messages.rs","room_actor.rs","server_state.rs","service_actor.rs"]};
sourcesIndex["jamsocket_stdio"] = {"name":"","files":["lib.rs"]};
sourcesIndex["jamsocket_wasm"] = {"name":"","files":["lib.rs","prelude.rs"]};
sourcesIndex["jamsocket_wasm_host"] = {"name":"","files":["lib.rs","wasm_host.rs","wasm_host_factory.rs"]};
sourcesIndex["jamsocket_wasm_macro"] = {"name":"","files":["lib.rs"]};
createSourceSidebar();
